set(_OLD_FIND_SUFFIXES ${CMAKE_FIND_LIBRARY_SUFFIXES})
set(CMAKE_FIND_LIBRARY_SUFFIXES ".lib" ".a" ".so" ".sl" ".dylib" ".dll.a")
FIND_PACKAGE(ZLIB REQUIRED)
set(CMAKE_FIND_LIBRARY_SUFFIXES ${_OLD_FIND_SUFFIXES})
unset(_OLD_FIND_SUFFIXES)

# using pkg-config
FIND_PACKAGE(PkgConfig) 
PKG_CHECK_MODULES(PC_QUAZIP QUIET QUAZIP) 
PKG_CHECK_MODULES(PC_QUAZIP1_QT5 QUIET quazip1-qt5) 

FIND_PATH(QUAZIP_INCLUDE_DIRS
    NAMES quazip.h
    HINTS ${QUAZIP_ROOT}/include
		  ${PC_QUAZIP_INCLUDEDIR}
          ${PC_QUAZIP_INCLUDE_DIRS}
		  ${PC_QUAZIP1_QT5_INCLUDEDIR}
          ${PC_QUAZIP1_QT5_INCLUDE_DIRS}
)

FIND_LIBRARY(QUAZIP_LIBRARIES
	WIN32_DEBUG_POSTFIX d
    NAMES libquazip libquazip5 quazip libquazip1-qt5
    HINTS ${QUAZIP_ROOT}/lib
 		${PC_QUAZIP_LIBDIR}
          ${PC_QUAZIP_LIBRARY_DIRS}
 		${PC_QUAZIP1_QT5_LIBDIR}
          ${PC_QUAZIP1_QT5_LIBRARY_DIRS}
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(QuaZip DEFAULT_MSG QUAZIP_INCLUDE_DIRS QUAZIP_LIBRARIES)
